name: Staging deployment
on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_HOST: 'https://api.staging.cryptoqr.co.za' # API host
      AWS_REGION: 'eu-west-2' # Define your AWS region
      S3_BUCKET: 'moneybadger-payments-page-staging' # Staging bucket

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # LTS version

      - name: Install dependencies
        run: npm ci

      # - name: Run audit
      #   run: npm audit

      - name: Build the project
        run: npm run build --if-present

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: aws s3 sync ./dist s3://${{ env.S3_BUCKET }} --delete
