name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # LTS version
      - run: npm ci # like npm install for CI
      - run: npm run build --if-present
      - run: npm test
