name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      HOST: 'https://api.staging.cryptoqr.co.za'

    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # LTS version
      - run: npm ci # like npm install for CI
      - run: HOST=${{ env.HOST }} npm run build --if-present
